// 定义描述
// generated by protogen, do not modify it
// 注释：.api文件中通过标识符引用的本项目或其他项目中定义的信息
import {
    MsgHeader
} from "../common.api";

// 注释：枚举输出
// protected n    module:tb-aiservern    获取前端通用配置n
export class ApiAIConfigGetFrontCommonReq {
    constructor(value?: any) {
        if (value == null) value = {};
        let obj = typeof value == 'string' ? JSON.parse(value) : value;
    }
}

export class AIConfigGetFrontCommonResData {
    "1": string; // 配置信息
    config: string; // 配置信息
    constructor(value?: any) {
        if (value == null) value = {};
        let obj = typeof value == 'string' ? JSON.parse(value) : value;
        this["1"] = obj["config"];

        this.config = obj["1"];

    }
}

export class ApiAIConfigGetFrontCommonRes extends MsgHeader {
    data: AIConfigGetFrontCommonResData;
    constructor(value?: any) {
        if (value == null) value = {};
        let obj = typeof value == 'string' ? JSON.parse(value) : value;
        super(obj);
        this.data = new AIConfigGetFrontCommonResData(obj["5"]);

    }
}


// protected n    module:tb-aiservern    通过key获取配置n
export class ApiAIConfigGetByKeyReq {
    "1": string; // 配置key
    constructor(value?: any) {
        if (value == null) value = {};
        let obj = typeof value == 'string' ? JSON.parse(value) : value;
        this["1"] = obj["key"];

    }
}

export class AIConfigGetByKeyResData {
    "1": string; // 配置信息
    config: string; // 配置信息
    constructor(value?: any) {
        if (value == null) value = {};
        let obj = typeof value == 'string' ? JSON.parse(value) : value;
        this["1"] = obj["config"];

        this.config = obj["1"];

    }
}

export class ApiAIConfigGetByKeyRes extends MsgHeader {
    data: AIConfigGetByKeyResData;
    constructor(value?: any) {
        if (value == null) value = {};
        let obj = typeof value == 'string' ? JSON.parse(value) : value;
        super(obj);
        this.data = new AIConfigGetByKeyResData(obj["5"]);

    }
}



