#!/bin/sh
echo "hello world"
# latestTag=$(git describe --tags --abbrev=0)
# latestTag=$(echo $latestTag | tr -d '\n')

# echo "\033[32m对比的文件"
# echo "\033[33m$latestTag \033[0m"
# echo "\033[32m========================\033[0m"

files=$(git diff --name-only --diff-filter=duxba main | sed -e "s/[[:space:]]/\n/g")
files=$(echo "$files" | sed -n -E '/\.(js|ts|tsx|wpy|vue)$/p') # only lint js, ts, tsx, wpy, vue files

echo "\033[32m对比的文件"
echo "\033[33m$ $files \033[0m"
echo "\033[32m========================\033[0m"

npx eslint $files

exit 0